# Created by: girgen
#
PORTNAME=	pingpong-aspell
PORTVERSION=	0.3
CATEGORIES=	pingpong
MASTER_SITES=	#
DISTFILES=	#
EXTRACT_ONLY=	#

MAINTAINER=	girgen@pingpong.net
COMMENT=	The meta-port for PING PONG application packages

NO_BUILD=	yes
PORTDATA=	installed.stamp

# for lang in af am ast az be bg bn br ca cs csb cy da el en eo es et fa fi fo fy ga gd gl grc gu gv hi hil hr hsb hy ia id is it kn ku ky la lt lv mi mk ml mn mr ms mt nb nds nl nn ny or pa qu ro rw sc sk sl sr sv sw ta te tet tk tl tn tr uz wa yi zu; do
# printf '\t${LOCALBASE}/share/aspell/%s.multi:textproc/%s-aspell \\\n' $lang $lang ; done

RUN_DEPENDS= \
	${LOCALBASE}/share/aspell/af.multi:textproc/af-aspell \
	${LOCALBASE}/share/aspell/am.multi:textproc/am-aspell \
	${LOCALBASE}/share/aspell/ast.multi:textproc/ast-aspell \
	${LOCALBASE}/share/aspell/az.multi:textproc/az-aspell \
	${LOCALBASE}/share/aspell/be.multi:textproc/be-aspell \
	${LOCALBASE}/share/aspell/bg.multi:textproc/bg-aspell \
	${LOCALBASE}/share/aspell/bn.multi:textproc/bn-aspell \
	${LOCALBASE}/share/aspell/br.multi:textproc/br-aspell \
	${LOCALBASE}/share/aspell/catalan.alias:textproc/ca-aspell \
	${LOCALBASE}/share/aspell/cs.multi:textproc/cs-aspell \
	${LOCALBASE}/share/aspell/csb.multi:textproc/csb-aspell \
	${LOCALBASE}/share/aspell/cy.multi:textproc/cy-aspell \
	${LOCALBASE}/share/aspell/da.multi:textproc/da-aspell \
	${LOCALBASE}/share/aspell/el.multi:textproc/el-aspell \
	${LOCALBASE}/share/aspell/en.multi:textproc/en-aspell \
	${LOCALBASE}/share/aspell/eo.multi:textproc/eo-aspell \
	${LOCALBASE}/share/aspell/es.multi:textproc/es-aspell \
	${LOCALBASE}/share/aspell/et.multi:textproc/et-aspell \
	${LOCALBASE}/share/aspell/fa.multi:textproc/fa-aspell \
	${LOCALBASE}/share/aspell/fi.multi:textproc/fi-aspell \
	${LOCALBASE}/share/aspell/fo.multi:textproc/fo-aspell \
	${LOCALBASE}/share/aspell/fy.multi:textproc/fy-aspell \
	${LOCALBASE}/share/aspell/ga.multi:textproc/ga-aspell \
	${LOCALBASE}/share/aspell/gd.multi:textproc/gd-aspell \
	${LOCALBASE}/share/aspell/gl.multi:textproc/gl-aspell \
	${LOCALBASE}/share/aspell/grc.multi:textproc/grc-aspell \
	${LOCALBASE}/share/aspell/gu.multi:textproc/gu-aspell \
	${LOCALBASE}/share/aspell/gv.multi:textproc/gv-aspell \
	${LOCALBASE}/share/aspell/hi.multi:textproc/hi-aspell \
	${LOCALBASE}/share/aspell/hil.multi:textproc/hil-aspell \
	${LOCALBASE}/share/aspell/hr.multi:textproc/hr-aspell \
	${LOCALBASE}/share/aspell/hsb.multi:textproc/hsb-aspell \
	${LOCALBASE}/share/aspell/hy.multi:textproc/hy-aspell \
	${LOCALBASE}/share/aspell/ia.multi:textproc/ia-aspell \
	${LOCALBASE}/share/aspell/id.multi:textproc/id-aspell \
	${LOCALBASE}/share/aspell/is.multi:textproc/is-aspell \
	${LOCALBASE}/share/aspell/it.multi:textproc/it-aspell \
	${LOCALBASE}/share/aspell/kn.multi:textproc/kn-aspell \
	${LOCALBASE}/share/aspell/ku.multi:textproc/ku-aspell \
	${LOCALBASE}/share/aspell/ky.multi:textproc/ky-aspell \
	${LOCALBASE}/share/aspell/la.multi:textproc/la-aspell \
	${LOCALBASE}/share/aspell/lt.multi:textproc/lt-aspell \
	${LOCALBASE}/share/aspell/lv.multi:textproc/lv-aspell \
	${LOCALBASE}/share/aspell/mi.multi:textproc/mi-aspell \
	${LOCALBASE}/share/aspell/mk.multi:textproc/mk-aspell \
	${LOCALBASE}/share/aspell/ml.multi:textproc/ml-aspell \
	${LOCALBASE}/share/aspell/mn.multi:textproc/mn-aspell \
	${LOCALBASE}/share/aspell/ms.multi:textproc/ms-aspell \
	${LOCALBASE}/share/aspell/mt.multi:textproc/mt-aspell \
	${LOCALBASE}/share/aspell/nb.multi:textproc/nb-aspell \
	${LOCALBASE}/share/aspell/nds.multi:textproc/nds-aspell \
	${LOCALBASE}/share/aspell/nl.multi:textproc/nl-aspell \
	${LOCALBASE}/share/aspell/nn.multi:textproc/nn-aspell \
	${LOCALBASE}/share/aspell/ny.multi:textproc/ny-aspell \
	${LOCALBASE}/share/aspell/or.multi:textproc/or-aspell \
	${LOCALBASE}/share/aspell/pa.multi:textproc/pa-aspell \
	${LOCALBASE}/share/aspell/qu.multi:textproc/qu-aspell \
	${LOCALBASE}/share/aspell/ro.multi:textproc/ro-aspell \
	${LOCALBASE}/share/aspell/rw.multi:textproc/rw-aspell \
	${LOCALBASE}/share/aspell/sc.multi:textproc/sc-aspell \
	${LOCALBASE}/share/aspell/sk.multi:textproc/sk-aspell \
	${LOCALBASE}/share/aspell/sl.multi:textproc/sl-aspell \
	${LOCALBASE}/share/aspell/sr.multi:textproc/sr-aspell \
	${LOCALBASE}/share/aspell/sv.multi:textproc/sv-aspell \
	${LOCALBASE}/share/aspell/sw.multi:textproc/sw-aspell \
	${LOCALBASE}/share/aspell/ta.multi:textproc/ta-aspell \
	${LOCALBASE}/share/aspell/te.multi:textproc/te-aspell \
	${LOCALBASE}/share/aspell/tet.multi:textproc/tet-aspell \
	${LOCALBASE}/share/aspell/tk.multi:textproc/tk-aspell \
	${LOCALBASE}/share/aspell/tl.multi:textproc/tl-aspell \
	${LOCALBASE}/share/aspell/tn.multi:textproc/tn-aspell \
	${LOCALBASE}/share/aspell/tr.multi:textproc/tr-aspell \
	${LOCALBASE}/share/aspell/uz.multi:textproc/uz-aspell \
	${LOCALBASE}/share/aspell/wa.multi:textproc/wa-aspell \
	${LOCALBASE}/share/aspell/yi.multi:textproc/yi-aspell \
	${LOCALBASE}/share/aspell/zu.multi:textproc/zu-aspell

do-install:
	${MKDIR} ${STAGEDIR}${DATADIR} && \
	${TOUCH} ${STAGEDIR}${DATADIR}/${PORTDATA}

.include <bsd.port.mk>
