#

    COMMENT = PING PONG specific ports

    SUBDIR += pingpong-app
    SUBDIR += pingpong-aspell
    SUBDIR += pingpong-database
    SUBDIR += pingpong-generic
    SUBDIR += pingpong-hardware

.include <bsd.port.subdir.mk>
