# $FreeBSD: head/archivers/Makefile 367830 2014-09-10 13:11:28Z bapt $
#

    COMMENT = PING PONG specific ports

    SUBDIR += pingpong-app
    SUBDIR += pingpong-aspell
    SUBDIR += pingpong-database
    SUBDIR += pingpong-generic
    SUBDIR += pingpong-hardware

.include <bsd.port.subdir.mk>
